//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ychet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RashodEntities : DbContext
    {
        public RashodEntities()
            : base("name=RashodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agents> Agents { get; set; }
        public virtual DbSet<Extradition> Extradition { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Shipment> Shipment { get; set; }
        public virtual DbSet<Summary_list> Summary_list { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
